version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome:4.25.0
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_VNC_NO_PASSWORD=1

  postgres:
    image: postgres:15
    container_name: t1-autotest-postgres
    environment:
      POSTGRES_DB: autotests
      POSTGRES_USER: autotest
      POSTGRES_PASSWORD: autotest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tests:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /project
    volumes:
      - ./:/project
      - maven-repo:/root/.m2
    environment:
      - MAVEN_OPTS=-Xmx1024m
      # ðŸ”¥ ÐŸÐ ÐžÐšÐ˜Ð”Ð«Ð’ÐÐ•Ðœ ÐÐÐ¡Ð¢Ð ÐžÐ™ÐšÐ˜ Ð‘Ð”
      - DB_URL=jdbc:postgresql://postgres:5432/autotests
      - DB_USER=autotest
      - DB_PASSWORD=autotest
    depends_on:
      - selenium
      - postgres
    command: >
      bash -lc "mvn -q clean test
      -DbaseUrl=https://t1.ru
      -DremoteUrl=http://selenium:4444/wd/hub
      -Dheadless=true
      -Dbrowser=chrome
      && mvn -q allure:report"

volumes:
  maven-repo:
  pgdata:
