name: UI Tests + Allure Pages

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'JUnit tags (e.g. SMOKE, REGRESSION, HDR)'
        required: false
        default: ''

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size=2g

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Clean allure results
        run: |
          rm -rf target/allure-results

      - name: Run UI tests
        run: |
          if [ -z "${{ github.event.inputs.tags }}" ]; then
            echo "Running ALL tests"
            mvn clean test \
              -DremoteUrl=http://localhost:4444/wd/hub \
              -Dheadless=true \
              -Denvironment=ci
          else
            echo "Running tests with tags: ${{ github.event.inputs.tags }}"
            mvn clean test \
              -DremoteUrl=http://localhost:4444/wd/hub \
              -Dheadless=true \
              -DincludeTags=${{ github.event.inputs.tags }}  \
              -Denvironment=ci
          fi

      - name: Generate Allure report
        if: always()
        run: |
          mvn allure:report

      - name: Debug allure folders
        if: always()
        run: |
          echo "=== target ==="
          ls -la target || true
          echo "=== target/site ==="
          ls -la target/site || true
          echo "=== target/site/allure-maven-plugin ==="
          ls -la target/site/allure-maven-plugin || true

      - name: Prepare Pages directory
        if: always()
        run: |
          mkdir -p pages
          if [ -d "target/site/allure-maven-plugin" ]; then
            cp -r target/site/allure-maven-plugin/* pages/
          else
            echo "<html><body><h1>Allure report was not generated</h1></body></html>" > pages/index.html
          fi

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

  deploy:
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4